/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BecomeProRouteImport } from './routes/become-pro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as ProfessionalSlugRouteImport } from './routes/professional.$slug'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard.verification'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard.quotes'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeProRoute = BecomeProRouteImport.update({
  id: '/become-pro',
  path: '/become-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalSlugRoute = ProfessionalSlugRouteImport.update({
  id: '/professional/$slug',
  path: '/professional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-pro': typeof BecomeProRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/professional/$slug': typeof ProfessionalSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-pro': typeof BecomeProRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/professional/$slug': typeof ProfessionalSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-pro': typeof BecomeProRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/professional/$slug': typeof ProfessionalSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-pro'
    | '/browse'
    | '/categories'
    | '/dashboard'
    | '/faq'
    | '/favorites'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/security'
    | '/dashboard/services'
    | '/dashboard/verification'
    | '/professional/$slug'
    | '/service/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/become-pro'
    | '/browse'
    | '/categories'
    | '/faq'
    | '/favorites'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/security'
    | '/dashboard/services'
    | '/dashboard/verification'
    | '/professional/$slug'
    | '/service/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/become-pro'
    | '/browse'
    | '/categories'
    | '/dashboard'
    | '/faq'
    | '/favorites'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/security'
    | '/dashboard/services'
    | '/dashboard/verification'
    | '/professional/$slug'
    | '/service/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BecomeProRoute: typeof BecomeProRoute
  BrowseRoute: typeof BrowseRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ProfessionalSlugRoute: typeof ProfessionalSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-pro': {
      id: '/become-pro'
      path: '/become-pro'
      fullPath: '/become-pro'
      preLoaderRoute: typeof BecomeProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/$slug': {
      id: '/professional/$slug'
      path: '/professional/$slug'
      fullPath: '/professional/$slug'
      preLoaderRoute: typeof ProfessionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BecomeProRoute: BecomeProRoute,
  BrowseRoute: BrowseRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ProfessionalSlugRoute: ProfessionalSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
